"""empty message

Revision ID: 7668e84381ec
Revises: 01e558319c4d
Create Date: 2021-09-26 16:39:10.375514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7668e84381ec'
down_revision = '01e558319c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchliststocks', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watchliststocks', 'company_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
