"""empty message

Revision ID: 53485097f838
Revises: ffdc0a98111c
Create Date: 2021-09-21 20:32:04.806154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53485097f838'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('friend1_id', sa.Integer(), nullable=True),
    sa.Column('friend2_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['friend2_id'], ['users.id'], )
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('trade_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trans_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.String(), nullable=False),
    sa.Column('transfer_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('transactionId', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['transactionId'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transactionId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('thumbs_up', sa.Boolean(), nullable=False),
    sa.Column('heart_react', sa.Boolean(), nullable=False),
    sa.Column('sad_react', sa.Boolean(), nullable=False),
    sa.Column('angry_react', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['transactionId'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchliststocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchListId', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['watchListId'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('users', sa.Column('holdings_value', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('users', sa.Column('createdAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'createdAt')
    op.drop_column('users', 'holdings_value')
    op.drop_column('users', 'balance')
    op.drop_table('watchliststocks')
    op.drop_table('reactions')
    op.drop_table('comments')
    op.drop_table('watchlists')
    op.drop_table('transfers')
    op.drop_table('transactions')
    op.drop_table('friends')
    # ### end Alembic commands ###
